### ISSUE TITLE
Multiple actions on Modal Close

### ISSUE THREAD

**Issue by ChopsKingsland** [ViktorMaric/HalfModal#2]
How do I run extra bits of code when the modal is closed? I would like to run `MKMapView.appearance().removeAnnotation(annotation)`

**Comment by ChopsKingsland** [comment]
@ViktorMaric is there anyway of doing this, otherwise there is one thing in my app that doesn't work properly?

**Comment by ViktorMaric** [comment]
Try with onDisappear() like this:
`HalfModalView(...).onDisappear { MKMapView.appearance().removeAnnotation(annotation) }`
