### ISSUE TITLE
Errors when compiling for Release scheme

### ISSUE THREAD

**Issue by fericit-bostan** [ViktorMaric/HalfModal#3]
I've added HalfModal to my project using the Swift Package Manager. Everything builds successfully so long as I use the Debug scheme. When I attempt to build a Release scheme I get compiler errors:

`❌  .../derived_data/SourcePackages/checkouts/HalfModal/Sources/HalfModal/BlurView.swift:18:37: cannot find type 'UIViewRepresentableContext' in scope
    public func makeUIView(context: UIViewRepresentableContext<BlurView>) -> UIView {
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
❌  .../derived_data/SourcePackages/checkouts/HalfModal/Sources/HalfModal/BlurView.swift:33:32: cannot find type 'UIViewRepresentableContext' in scope
                      context: UIViewRepresentableContext<BlurView>) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
❌  .../derived_data/SourcePackages/checkouts/HalfModal/Sources/HalfModal/BlurView.swift:14:25: cannot find type 'UIViewRepresentable' in scope
public struct BlurView: UIViewRepresentable {
                        ^~~~~~~~~~~~~~~~~~~
❌  .../derived_data/SourcePackages/checkouts/HalfModal/Sources/HalfModal/HalfModalContent.swift:17:24: cannot find type 'AnyView' in scope
    var priorButtons: [AnyView]?
                       ^~~~~~~`

This occurs when building using both Xcode and fastlane. 
Xcode: Version 12.4 (12D4e)
iOS Deployment Target: 14.4

Any help would be greatly appreciates at this point.
Thanks....

![Screen Shot 2021-03-11 at 10 36 11](https://user-images.githubusercontent.com/1659966/110837058-a6f77b80-8255-11eb-96ee-aac147201278.png)

**Comment by ViktorMaric** [comment]
I advise you not to use SwiftPackageManager. Just copy the files from the sources/HalfModal to your project.
You should copy four files: BlurView.swift, HalfModalContent.swift, HalfModalView.swift, ModalButtonView.swift

**Comment by fericit-bostan** [comment]
Thanks for the update.
